# Based off of this image: https://hub.docker.com/_/microsoft-powershell
FROM mcr.microsoft.com/powershell:latest
RUN pwsh -command "Write-Host 'Docker Container has started'"
# Install required modules
RUN pwsh -command "Install-Module Microsoft.PowerShell.SecretManagement, Microsoft.PowerShell.SecretStore -ErrorAction 'Stop'"
RUN pwsh -command "Write-Host 'Install-Module has been invoked.'"

VOLUME ["/home/powershell/secrets"]
RUN pwsh -command "Write-Host 'Volume set.'"

EXPOSE 8126:8126
RUN pwsh -command "Write-Host 'Ports Exposed'"

LABEL jevans <jeff.evans@jevans.dev>